#include <iostream>
#include <Windows.h>
#include <TlHelp32.h>
#include "Offsets.h"
#include "localPlayer.h"
#include "glowingEffect.h"
#include "hwidVerification.h"
#include <tchar.h>
#include <intrin.h>